"""empty message

Revision ID: 4783d6dedf1b
Revises: 
Create Date: 2020-08-20 13:13:29.607391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4783d6dedf1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('home_page', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_home_page'), 'resource', ['home_page'], unique=True)
    op.create_index(op.f('ix_resource_title'), 'resource', ['title'], unique=True)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(length=120), nullable=True),
    sa.Column('link', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_timestamp'), 'news', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_timestamp'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_resource_title'), table_name='resource')
    op.drop_index(op.f('ix_resource_home_page'), table_name='resource')
    op.drop_table('resource')
    # ### end Alembic commands ###
