"""empty message

Revision ID: 76f94842192b
Revises: 4783d6dedf1b
Create Date: 2020-08-20 13:30:12.882449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f94842192b'
down_revision = '4783d6dedf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_news_header'), 'news', ['header'], unique=True)
    op.create_index(op.f('ix_news_link'), 'news', ['link'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_link'), table_name='news')
    op.drop_index(op.f('ix_news_header'), table_name='news')
    # ### end Alembic commands ###
