"""add body to table News

Revision ID: f5afe8cbdd01
Revises: 76f94842192b
Create Date: 2020-11-02 13:36:19.915299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5afe8cbdd01'
down_revision = '76f94842192b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'body')
    # ### end Alembic commands ###
